### ISSUE TITLE
Friend list UI not visible

### ISSUE THREAD

**Issue by BigPino67** [timebomb0/HordesUIMod#18]
I am able to add a friend when he writes in the chat.

When I click on the "F" button in the top right menu, no friend list UI is shown, nothing happens.

My friend has the same issue. What are we doing wrong?

**Comment by TimeBomb** [comment]
This was fixed with the last update on greasyfork.

**Comment by timebomb0** [comment]
Heyo, thanks for reporting this. We fixed this with the last update on GreasyFork that occured a little while back.
