### ISSUE TITLE
New Feature: Clean up highlighted items when shift is held

### ISSUE THREAD

**Issue by GlassBBQ** [timebomb0/HordesUIMod#22]
With high item find loot tends to get very messy when holding down shift, stacking on top of each other.

Any chance to fix these up so we can loot faster and more efficiently (maybe add transparency options too)

**Comment by timebomb0** [comment]
Heya, thanks for the feedback. Definitely a solid suggestion.
In the case of this mod, we're unable to modify the part of the game that displays the loot on the ground. This mod modifies what'd technically be considered the UI - things like the chat and most of the games windows, like the inventory.

The loot you see on the ground, and the names you see when holding shift, are actually part of the game rendering logic - the same part of tech that handles rendering characters, the world, etc. This mod isn't able to change those things.

I'd bring up your suggestion in the Hordes.io discord if you haven't already - would be nice to have some control over this for sure. Best of luck and thanks for the feedback!

**Comment by Azzy1259** [comment]
Ok great, thanks for the response!
