### ISSUE TITLE
Player Target Frame Issue

### ISSUE THREAD

**Issue by thomasthebear** [timebomb0/HordesUIMod#9]
Currently, if you move the location of the TargetFrame, it will stay in the correct location until you untarget anything. When retargeting, it will reposition to the Default position unless you right click on it, in which case it will return to the location it was moved to.

**Comment by timebomb0** [comment]
Thanks for the report, will add it to the list of known issues and see if I can figure this out over the weekend.

**Comment by timebomb0** [comment]
This should've been fixed as of v1.2.2 :)
